modLoader="javafml"
loaderVersion="[28,)"
license="LGPL-3.0"
[[mods]]
modId="wings"
version="${file.jarVersion}"
displayName="Wings and Claws"
credits="Mr. Esuoh, Redkoopa, Ninni, Mnesikos, RonitrocketYT, SDOAJ, sarx, Proddy"
authors="Coda, Tazz, Ms. Random"
description=""
[[dependencies.wings]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
